# Generated by Django 4.1.1 on 2022-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bois compressé', 'Bois Compressé'), ('Granulés de bois', 'Granulés de bois'), ('Bois de chauffage', 'Bois de chauffage')], default='Bois de chauffage', max_length=30),
        ),
    ]
